/* MULTIPLAS CONDICOES E PERFORMANCE */
IF 1 = 1 -- SE
	PRINT 'VERDADEIRO'


-- TESTANDO CONDICOES COM RO (OU)
IF (1 = 1) OR (2 = 2) -- OR -> PELO MENOS UMA DAS CONDICOES PRECISA SER VERDADEIRA
    PRINT 'VERDADEIRO'
    GO


IF (1 = 0) OR (2 = 2) -- OR -> PELO MENOS UMA DAS CONDICOES PRECISA SER VERDADEIRA
    PRINT 'VERDADEIRO'
    GO


IF (1 = 0) OR (2 = 6) OR (5 = 5) -- OR -> PELO MENOS UMA DAS CONDICOES PRECISA SER VERDADEIRA
    PRINT 'VERDADEIRO'
    GO


IF (1 = 0) OR (2 = 3) -- OR -> PELO MENOS UMA DAS CONDICOES PRECISA SER VERDADEIRA
    PRINT 'VERDADEIRO'
ELSE
   PRINT 'FALSO'
   GO


/* AND - TODOS OS TESTES EXECUTADOS PRECISAM SER VERDADEIROS */
IF (1 = 1) AND (2 = 2) -- AND -> TODOS OS TESTES EXECUTADOS PRECISAM SER VERDADEIROS
    PRINT 'VERDADEIRO'
    GO


IF (1 = 0) AND (2 = 2) -- AND -> TODOS OS TESTES EXECUTADOS PRECISAM SER VERDADEIROS
    PRINT 'VERDADEIRO'
    GO


IF (1 = 0) AND (2 = 6) AND (5 = 5) -- AND -> TODOS OS TESTES EXECUTADOS PRECISAM SER VERDADEIROS
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO


IF (1 = 1) AND (2 = 2) AND (5 = 5) -- AND -> TODOS OS TESTES EXECUTADOS PRECISAM SER VERDADEIROS
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO


/* DO PONTO DE VISTA DE PERFORMANCE */

/* COLOQUE AS COISAS QUE VOCE SABE QUE RETORNARAO VERDADEIRO SEMPRE NA PRIMEIRA AVALIACAO -- OR */

IF 1 = 1 -- ESEE TESTE DEMORA 0.2
   OR 7 = 7 -- ESEE TESTE DEMORA 10 MINUTOS
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO


IF 7 = 7 OR 1 = 1
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO


IF (7 = 9 OR 1 = 1) AND 1 = 1
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO


IF (7 = 9 OR 1 = 1) AND 1 = 1 AND 1 = 5
    PRINT 'VERDADEIRO'
ELSE
    PRINT 'FALSO'
    GO