/* VARIAVEIS E ESCOPO

VARIAVEL E UM ESPACO DE ARMAZENAMENTO ALOCADO NA MEMORIA, E TEMPORARIO.
ESCALARES E TABELAS
VARIAVEL ESCALAR ARMAZENA UM UNICO VALOR
VARIAVEIS ESCALARES SAO ACESSÍVEIS SOMENTE DENTRO DA SUA SECAO
*/
DECLARE @VARDOROMULO INT
	SET @VARDOROMULO = 10
	PRINT @VARDOROMULO
	SELECT @VARDOROMULO
GO	-- DESTROI QUALQUER VARIAVEL CRIADA NA BATCH


DECLARE @VARDOROMULO INT
	SET @VARDOROMULO = 10
GO
	PRINT @VARDOROMULO
	SELECT @VARDOROMULO
GO


DECLARE @VARDOROMULO INT
	SET @VARDOROMULO = 10
	PRINT @VARDOROMULO
	SELECT @VARDOROMULO AS VARIAVEL
GO


DECLARE @A INT = 5
DECLARE @B INT = 10

IF @A = @B	-- ESSE TESTE DEMORA 0.2 RETORNA TRUE 90%
	PRINT 'VERDADEIRO'
ELSE
	PRINT 'FALSO'


DECLARE @MYVAR INT = 6
	SET @MYVAR = @MYVAR + 1
	PRINT @MYVAR
GO


DECLARE @MYVAR INT  -- DECLARATIVA
	SET @MYVAR = 6
	SET @MYVAR = @MYVAR + 1
	PRINT @MYVAR
GO


-- DECLARO COM SELECT
DECLARE @MYVAR INT -- DECLARATIVA
	SELECT @MYVAR = 6
	SELECT @MYVAR = @MYVAR + 1
	PRINT @MYVAR
GO


-- SELECT É UTILIZADO PARA ATRIBUIR QUANDO O RESULTADO VEM DE UMA QUERY
-- SET É UTILIZADO QUANDO ATRIBUIMOS UM VALOR LITERAL E TAMBEM VALORES VINDOS DE FUNCOES
DECLARE @MAXCUSTOMERID INT

SELECT @MAXCUSTOMERID = MAX([CustomerKey])
FROM [AdventureWorksDW2017].[dbo].[DimCustomer]

SELECT @MAXCUSTOMERID
GO


SELECT MAX([CustomerKey])
FROM [AdventureWorksDW2017].[dbo].[DimCustomer]


/* SET */
DECLARE @HOJE DATETIME
SET @HOJE = GETDATE()
SELECT @HOJE
PRINT @HOJE
GO


/* VARIAS ATRIBUICOES */
DECLARE @V1 INT
      , @V2 INT
	  , @V3 VARCHAR(30)
	  , @V4 MONEY = 2312.90
GO

SELECT @V1 = 1, @V2 = 2
PRINT @V1
GO