/*
O TIPO STRING (VARCHAR)
*/
DECLARE @X CHAR = 'FELICTY SMOKE'
SELECT @X

DECLARE @Y VARCHAR = 'ARROW'
SELECT @X AS NOME, @Y AS SOBRENOME
GO

/*
DECLARANDO O TAMANHO
*/
DECLARE @X CHAR(4) = 'FELICTY SMOKE'
SELECT @X

DECLARE @Y VARCHAR(4) = 'ARROW'
SELECT @X AS NOME, @Y AS SOBRENOME


-- VERIFICANDO O TAMANHO
SELECT
    DATALENGTH(@X) AS TAMANHO_X
  , DATALENGTH(@Y) AS TAMANHO_Y

SELECT
    DATALENGTH(@X) AS TAMANHO_X
  , DATALENGTH(@Y) AS TAMANHO_Y
  , DATALENGTH('ARROW') AS TAMANHO_LITERAL
GO

/*
CHAR E VARCHAR NAO SAO UNICODE E NCHAR E NVARCHAR SAO UNICODE
*/
DECLARE @X NCHAR(2000) = 'FELICTY SMOKE'
DECLARE @Y NVARCHAR(2000) = 'ARROW'
DECLARE @X_1 CHAR(2000) = 'FELICTY SMOKE'
DECLARE @Y_1 VARCHAR(2000) = 'ARROW'

SELECT
    @X AS NOME
  , DATALENGTH(@X) AS TAMANHO_X
  , @Y AS SOBRENOME
  , DATALENGTH(@Y) AS TAMANHO_Y
  , @X_1 AS NOME_1
  , DATALENGTH(@X_1) AS TAMANHO_X_1
  , @Y_1 AS SOBRENOME_1
  , DATALENGTH(@Y_1) AS TAMANHO_Y_1


/*
UM BYTE POR CARACTER
8 BITS EM 1 BYTE (0, 1)
256 CARACTERES UNICOS EM UMA COLUNA
26 + 10 + fF aA Áá + CHINES + RUSSO
UNICODE
*/
DECLARE @CHINES VARCHAR(128) = '汉字'

SELECT
    @CHINES AS TEXTO
  , DATALENGTH(@CHINES) AS TAMANHO_CHINES
GO