-- NUMEROS
DECLARE @A BIGINT = 1       -- BIG NUMBER
      , @B INT = 1          --  +- 2 BILHOES
      , @C SMALLINT = 1     -- +- 32 MIL
      , @D TINYINT = 1      -- 0 A 255 - 1 BYTE
      , @E BIT = 1          -- 0 OU 1

SELECT
    @A AS BIGINT_VALOR
  , @B AS INT_VALOR
  , @C AS SMALLINT_VALOR
  , @D AS TINYINT_VALOR
  , @E AS BIT_VALOR


SELECT
    DATALENGTH(@A) AS BIGINT_TAMANHO
  , DATALENGTH(@B) AS INT_TAMANHO
  , DATALENGTH(@C) AS SMALLINT_TAMANHO
  , DATALENGTH(@D) AS TINYINT_TAMANHO
  , DATALENGTH(@E) AS BIT_TAMANHO
GO

-- TIPOS APROXIMADOS
DECLARE @F MONEY = 123456.7891          -- 8 BYTES +- 9 BIG NUMBERS
      , @G SMALLMONEY = 123456.7891     -- 4 BYTES +- 200K

SELECT
    @F AS MONEY_VALOR
  , @G AS SMALLMONEY_VALOR

SELECT
    DATALENGTH(@F) AS MONEY_TAMANHO
  , DATALENGTH(@G) AS SMALLMONEY_TAMANHO
GO


DECLARE @F MONEY = 123456789.7891          -- 8 BYTES +- 9 BIG NUMBERS
      , @G SMALLMONEY = 123456789.7891     -- 4 BYTES +- 200K

SELECT
    @F AS MONEY_VALOR
  , @G AS SMALLMONEY_VALOR

SELECT
    DATALENGTH(@F) AS MONEY_TAMANHO
  , DATALENGTH(@G) AS SMALLMONEY_TAMANHO
GO

-- PRECISAO (DECIMAIS)
DECLARE @PRECO MONEY = 1.95

SELECT
        @PRECO AS PRECO_VALOR
GO

-- QUANDO EU TENHO VALORES DE DUAS CASAS DECIMAIS, EU PREFIRO UTILIZAR DECIMAL