-- QUANDO EU TENHO VALORES DE DUAS CASAS DECIMAIS, EU PREFIRO UTILIZAR DECIMAL
-- 10 NUMERO TOTAL DE CASAS DECIMAIS INCLUINDO O PONTO
DECLARE @VALOR DECIMAL(10, 2) = 1.95

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO


DECLARE @VALOR DECIMAL(10, 2) = 1.95774587

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO

-- TENDO O TAMANHO DO MONEY
DECLARE @VALOR DECIMAL(18, 4) = 1.95774587

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO


DECLARE @VALOR DECIMAL(18, 4) = 1.9500

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO


DECLARE @VALOR DECIMAL(18, 19) = 1.9500 -- ERRO: A escala (19) não pode ser maior que a precisão (18)

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO


DECLARE @VALOR FLOAT(24) = 1.9500

SELECT
    @VALOR AS VALOR_COMO_DECIMAL
  , DATALENGTH(@VALOR) AS TAMANHO_EM_BYTES_DO_DECIMAL
GO