-- UTC TIME

-- https://pt.wikipedia.org/wiki/Tempo_Universal_Coordenado
-- https://time.is/pt/UTC

SELECT
    GETDATE()     AS DataHoraLocal  -- RETORNA DATA / HORA DO SERVIDOR (LOCAL)
  , GETUTCDATE()  AS DataHoraUTC    -- RETORNA A DATA HORA EM UTC (TEMPO UNIVERSAL COORDENADO)
  , SYSDATETIME() AS DataHoraLocal2 -- RETORNA DATA / HORA DO SERVIDOR (LOCAL) COM PRECISÃO MAIOR. NANOSEGUNDOS


DECLARE @A DATETIME2 =  GETDATE()   -- TRUNCAR OS NANOSEGUNDOS
SELECT
    @A AS DataHoraLocal
GO


DECLARE @B DATETIME2 = SYSDATETIME()    -- ARMAZENA CORRETAMENTE COM 7 CASAS DECIMAIS
SELECT
    @B AS DataHoraLocal2
GO


DECLARE @B DATETIME2(4) = SYSDATETIME()   -- ORDENADO PARA O TIPOO QUE ELE TENHA APENAS 4 CASAS DE PRECISÃO
SELECT
    @B AS DataHoraLocal2
GO


-- SYDATIMEOFFSET = DATA / HORA COM FUSO HORÁRIO
SELECT
    SYSDATETIME()       AS DataHoraLocal
  , SYSDATETIMEOFFSET() AS DataHoraComFuso  -- TRAZ O FUSO HORARIO EM RELACAO AO UTC
GO


DECLARE @A DATETIME2      = SYSDATETIME()
      , @B DATETIMEOFFSET = SYSDATETIME()
      , @C DATETIMEOFFSET = SYSDATETIMEOFFSET()

SELECT
    @A                         AS DataHoraLocal
  , @B                         AS DataHoraComFuso1
  , @C                         AS DataHoraComFuso2
  , SWITCHOFFSET(@C, '+05:00') AS DataHoraUTC
  , DATEADD(HOUR, 10, @B)      AS DataHoraComFusoAlterado   -- CUIDADO POIS ELE SOMA AS HORAS CORRETAMENTE MAS TRAZ O UTC ZERADO
GO